on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'ref to build'
        required: false
        type: string
  schedule:
    - cron:  '0 1 * * *'
  
concurrency:
  group: "pages"
  cancel-in-progress: true

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    env:
      DIR: './crates/compiler/checkmate/www'
    defaults:
      run:
        working-directory: ${{ env.DIR }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: 'roc-lang/roc'
          ref: ${{inputs.ref || 'main'}}
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: npm
          cache-dependency-path: ${{ env.DIR }}/package-lock.json
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Install Dependencies
        run: npm ci
      - name: Build
        run:
          PACKAGE_JSON=$(cat package.json)

          echo "$PACKAGE_JSON" | jq --arg homepage "https://ayazhafiz.com/checkmate" '. + {homepage:$homepage}' > package.json

          npx react-scripts build
        env:
          # Allow warnings
          CI: false
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ${{ env.DIR }}/build
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
